_target_: clean_SemiSL.task.registry.load_task
name: mnist
root: "data"
download: True
type: image_classification
seed: 0
labeling_ratio: 0.1
num_classes: 10
metrics:
  acc:
    _target_: clean_SemiSL.utils.metrics_utils.classification_top_1_accuracy
  acc@5:
    _target_: clean_SemiSL.utils.metrics_utils.classification_top_5_accuracy
