defaults:
  - task: cifar10
  - _self_

model:
  _target_: clean_SemiSL.model.custom.ResNet32x32
  block_name: "shake"
  layers: [4,4,4]
  num_classes: 10
  channels: 48
  downsample: "shift_conv"

optimizer:
  _target_: torch.optim.SGD
  weight_decay: 1e-4
  momentum: 0.9
  nesterov: True

hyperparams:
  workers: 4 
  num_iterations: 500_000
  eval_frequency: 1_000
  discard_unlabeled: False
  batch_size: 200
  labeled_batch_size: 100
  
  lr:
    v0: 0.1
    vf: 0.01
    ramp_start: 0
    ramp_end: 500_000 
  
  regularization_name: "pseudo_label"
  sharpening_temperature: 0.5
  regularization_coeff: 
    v0: 0.0
    vf: 0.5
    ramp_start: 0
    ramp_end: 200_000 

device: "cuda"
verbose: True
log_wandb: True
wandb:
  project_name: "clean_SemiSL"
run_name: "cifar10_pseudo_label"
