defaults:
  - _self_
  - task: cifar10

model:
  _target_: clean_SemiSL.model.custom.ResNet32x32
  block_name: "shake"
  layers: [4,4,4]
  num_classes: 10
  channels: 48
  downsample: "shift_conv"

hyperparams:
  workers: 4 
  num_epochs: 50
  discard_unlabeled: False
  batch_size: 64 
  labeled_batch_size: 32
  optimizer: "adam"
  weight_decay: 1e-5

  lr:
    v0: 0.001
    vf: 0.0001
    ramp_start: 0
    ramp_end: 50

  sharpening_temperature: 0.1
  regularization_coeff: 
    v0: 0.0
    vf: 0.2
    ramp_start: 10
    ramp_end: 20

device: "cuda"
verbose: True
log_wandb: True
wandb:
  project_name: "clean_SemiSL"
run_name: "pseudo_label"
