defaults:
  - task: cifar10

model:
  _target_: clean_SemiSL.model.custom.ResNet32x32
  block_name: "shake"
  layers: [4,4,4]
  num_classes: 10
  channels: 96
  downsample: "shift_conv"

device: cuda
workers: 1 
num_epochs: 100
batch_size: 20
labeled_batch_size: 10
optimizer: "adam"
lr: 0.01
weight_decay: 1e-5 
consistency_coeff: 1.0
verbose: True

