defaults:
  - task: cifar10
  - _self_

task:
  labeling_ratio: 0.08

model:
  _target_: clean_SemiSL.model.custom.ResNet32x32
  block_name: "shake"
  layers: [4,4,4]
  num_classes: 10
  channels: 48
  downsample: "shift_conv"

optimizer:
  name: "adam"
  weight_decay: 1e-4

hyperparams:
  workers: 4 
  num_iterations: 200_000
  eval_frequency: 1_000
  discard_unlabeled: False
  batch_size: 200
  labeled_batch_size: 100
  sharpening_temperature: 0.5
  
  lr:
    schedule_type: "decay"
    v0: 0.003
    decay_factor: 0.2
    decay_period: 0.5 
    schedule_start: 0.0
    schedule_end: 1.0

  regularization_coeff: 
    schedule_type: "constant" 
    v0: 0.1 

device: "cuda"
verbose: True
log_wandb: True
wandb:
  project_name: "clean_SemiSL"
run_name: "cifar10_entmin"
