defaults:
  - task: cifar10
  - _self_

task:
  labeling_ratio: 0.08

model:
  _target_: clean_SemiSL.model.custom.ResNet32x32
  block_name: "shake"
  layers: [4,4,4]
  num_classes: 10
  channels: 48
  downsample: "shift_conv"

optimizer:
  name: "sgd"
  weight_decay: 1e-4
  nesterov: True
  momentum: 0.9

hyperparams:
  workers: 4 
  num_iterations: 50_000
  eval_frequency: 1_000
  discard_unlabeled: True
  batch_size: 200
  label_smoothing: 0.1
  
  lr:
    schedule_type: "decay"
    v0: 0.1
    decay_factor: 0.2
    decay_period: 0.5
    schedule_start: 0.0
    schedule_end: 1.0

  regularization_coeff: 
    schedule_type: "linear" 
    v0: 0.0
    vf: 5.0
    schedule_start: 0.0
    schedule_end: 0.2

device: "cuda"
verbose: True
log_wandb: True
wandb:
  project_name: "clean_SemiSL"
run_name: "cifar10_label_only"
